import { saleItem, FilterSets } from "../types/index";
export const saleItems: Array<saleItem> = [
  {
    title: "LG<br>32LM6350PLA",
    imageURL: "./assets/tvimages/LG 32LM6350PLA.jpeg",
    brand: "LG",
    size: "32",
    year: "2019",
    color: "black",
    count: "3",
    price: "450",
  },
  {
    title: "LG<br>43NANO776PA",
    imageURL: "./assets/tvimages/LG 43NANO776PA.jpeg",
    brand: "LG",
    size: "43",
    year: "2021",
    color: "grey",
    count: "4",
    price: "750",
  },
  {
    title: "LG<br>43UP78006LC",
    imageURL: "./assets/tvimages/LG 43UP78006LC.jpeg",
    brand: "LG",
    size: "43",
    year: "2019",
    color: "black",
    count: "2",
    price: "500",
  },
  {
    title: "LG<br>43UP78806DT",
    imageURL: "./assets/tvimages/LG 43UP78006LC.jpeg",
    brand: "LG",
    size: "43",
    year: "2022",
    color: "black",
    count: "2",
    price: "550",
  },
  {
    title: "LG<br>50NANO866PA",
    imageURL: "./assets/tvimages/LG 50NANO866PA.jpeg",
    brand: "LG",
    size: "50",
    year: "2021",
    color: "black",
    count: "5",
    price: "1000",
  },
  {
    title: "LG<br>50UP75006LF",
    imageURL: "./assets/tvimages/LG 50UP75006LF.jpeg",
    brand: "LG",
    size: "50",
    year: "2021",
    color: "grey",
    count: "2",
    price: "740",
  },
  {
    title: "LG<br>OLED55C1RLA",
    imageURL: "./assets/tvimages/LG OLED55C1RLA.jpeg",
    brand: "LG",
    size: "55",
    year: "2022",
    color: "black",
    count: "1",
    price: "1600",
  },
  {
    title: "Samsung<br>QE55QN90AAU",
    imageURL: "./assets/tvimages/Samsung QE55QN90AAU.png",
    brand: "Samsung",
    size: "55",
    year: "2022",
    color: "grey",
    count: "3",
    price: "1500",
  },
  {
    title: "Samsung<br>QE85QN85AAU",
    imageURL: "./assets/tvimages/Samsung QE85QN85AAU.jpeg",
    brand: "Samsung",
    size: "85",
    year: "2022",
    color: "black",
    count: "1",
    price: "7500",
  },
  {
    title: "Samsung<br>UE32T5300AU",
    imageURL: "./assets/tvimages/Samsung UE32T5300AU.jpeg",
    brand: "Samsung",
    size: "32",
    year: "2020",
    color: "black",
    count: "4",
    price: "400",
  },
  {
    title: "Samsung<br>UE43AU9000U",
    imageURL: "./assets/tvimages/Samsung UE43AU9000U.jpeg",
    brand: "Samsung",
    size: "43",
    year: "2019",
    color: "black",
    count: "2",
    price: "799",
  },
  {
    title: "Samsung<br>UE50AU7100U",
    imageURL: "./assets/tvimages/Samsung UE50AU7100U.jpeg",
    brand: "Samsung",
    size: "50",
    year: "2021",
    color: "grey",
    count: "3",
    price: "850",
  },
  {
    title: "Sony<br>KD-43X85TJ",
    imageURL: "./assets/tvimages/Sony KD-43X85TJ.jpeg",
    brand: "Sony",
    size: "43",
    year: "2021",
    color: "black",
    count: "3",
    price: "1000",
  },
  {
    title: "Sony<br>XR-55A80J",
    imageURL: "./assets/tvimages/Sony XR-55A80J OLED.jpeg",
    brand: "Sony",
    size: "55",
    year: "2021",
    color: "black",
    count: "1",
    price: "2000",
  },
  {
    title: "Sony<br>XR-55X90J",
    imageURL: "./assets/tvimages/Sony XR-55X90J.jpeg",
    brand: "Sony",
    size: "55",
    year: "2021",
    color: "grey",
    count: "4",
    price: "1200",
  },
  {
    title: "Xiaomi<br>Mi TV 4A 55",
    imageURL: "./assets/tvimages/Xiaomi Mi TV 4A 55.jpeg",
    brand: "Xiaomi",
    size: "55",
    year: "2020",
    color: "black",
    count: "6",
    price: "790",
  },
  {
    title: "Xiaomi<br>MI TV 4S 50",
    imageURL: "./assets/tvimages/Xiaomi MI TV 4S 50.jpeg",
    brand: "Xiaomi",
    size: "50",
    year: "2019",
    color: "grey",
    count: "2",
    price: "850",
  },
  {
    title: "Xiaomi<br>MI TV P1 50",
    imageURL: "./assets/tvimages/Xiaomi MI TV P1 50.jpeg",
    brand: "Xiaomi",
    size: "50",
    year: "2021",
    color: "black",
    count: "5",
    price: "600",
  },
];
export const filterSets: FilterSets = {
  brand: [],
  year: [],
  color: [],
  inchMin: "32",
  inchMax: "85",
  priceMin: "100",
  priceMax: "10000",
  sorts: "titleaz",
  title: [],
  count: 0,
};
